### ISSUE TITLE
R requirements (< 4.0 ?) and Rniftilib

### ISSUE THREAD

**Issue by octomike** [IBIC/neuropointillist#12]
Hi,

so we are trying to install this package by following [the installation instructions](http://ibic.github.io/neuropointillist/installation.html), but running `npoint` on the example.rawfmri results in:

```
$ npoint
Error in mask[, , ] : object of type 'externalptr' is not subsettable
Calls: as.vector
Execution halted
```

It seems that `nifti.image.read()` does not return a usble/expected object, at least not with our R 4.0+ environments. R 3.6.3 works fine.
Is that a known issue? Do you know if Rniftilib is compatible with R 4.0+? I'm having a hard time finding some maintainer or current source for that library.

**Comment by madhyastha** [comment]
Thank you for bringing this to my attention. I will look into it and try to
come up with a fix.

**Comment by madhyastha** [comment]
This has been addressed by moving to the RNifti package in the permutationtesting branch. I am still testing it but I would welcome anyone willing to beta test it!

**Comment by octomike** [comment]
(doing some housekeeping)

I just tested this again:

```
[mk@leslie ~/.../neuropointillist/example.rawfmri (master)] ../npoint
Reading 2 data sets.
Allocating memory for data.
Reading in data.
	++Working on dataset 1 
	++Working on dataset 2 
          used (Mb) gc trigger  (Mb) max used  (Mb)
Ncells  413868 22.2     840465  44.9   665800  35.6
Vcells 1871951 14.3   33423838 255.1 34806161 265.6
no. of vertices 792 
size 79 
no. of jobs 10
```

Looking good, will close this issue :)
