### ISSUE TITLE
Error in results : incorrect number of dimensions 

### ISSUE THREAD

**Issue by bel8** [IBIC/neuropointillist#4]
Error in results[, 1] : incorrect number of dimensions 
Calls: npointWriteOutputFiles

This error was presented when the output of processvoxel contained only 1 value. This could be tricked by duplicated the single value twice. 

EX:
from retvals <- (1) to retvals <-(1,1)
names(retvals) <- ("output","output")

**Comment by madhyastha** [comment]
Fixed to allow one or many results to be returned.
