### ISSUE TITLE
Error on first execution of ./runme.local

### ISSUE THREAD

**Issue by emilytwood** [IBIC/neuropointillist#7]
_Error from first ./runme.local execution:_
make: *** No rule to make target `model_Split0001p-task.nii.gz', needed by` model_Splitp-task.nii.gz'.  Stop.
_Stop seems to occur right before running npointmerge._

_It works when we run ./runme.local a second time, or if npointmerge is called directly:_

npointmerge model_Splittstat-task.nii.gz *tstat-task.nii.gz

**Comment by madhyastha** [comment]
This error was due to the fact that I avoided a multiple target situation in make, which would cause the same rule to fire once for each output file (incorrect behavior). I fixed this by using a pattern rule, which only fires once for all targets.
